# headers and icon 
title: DJ Doherty
info: BS Computer Engineering'24 @ Binghamton University
icon-pic: assets/img/mandu_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
